name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run linter
        run: |
          GO111MODULE=off go get golang.org/x/lint/golint
          make lint

      - name: Run test
        run: make test

